-- Seed comprehensive curriculum data for all 7 careers
-- Each career has 9 semesters, with semester 9 being Residencias Profesionales
USE control_escolar;

-- First, insert common subjects that all careers share
INSERT INTO materias (nombre, clave) VALUES
-- Matemáticas básicas
('Cálculo Diferencial', 'MAT-1001'),
('Cálculo Integral', 'MAT-1002'),
('Cálculo Vectorial', 'MAT-1003'),
('Álgebra Lineal', 'MAT-1004'),
('Ecuaciones Diferenciales', 'MAT-1005'),
('Probabilidad y Estadística', 'MAT-1006'),

-- Inglés (10 niveles)
('Inglés I', 'ING-1001'),
('Inglés II', 'ING-1002'),
('Inglés III', 'ING-1003'),
('Inglés IV', 'ING-1004'),
('Inglés V', 'ING-1005'),
('Inglés VI', 'ING-1006'),
('Inglés VII', 'ING-1007'),
('Inglés VIII', 'ING-1008'),
('Inglés IX', 'ING-1009'),
('Inglés X', 'ING-1010'),

-- Ciencias básicas
('Química', 'QUI-1001'),
('Física I', 'FIS-1001'),
('Física II', 'FIS-1002'),

-- Formación general
('Taller de Ética', 'ETI-1001'),
('Desarrollo Sustentable', 'DES-1001'),
('Fundamentos de Investigación', 'INV-1001'),
('Taller de Investigación I', 'INV-1002'),
('Taller de Investigación II', 'INV-1003'),
('Gestión de Proyectos', 'ADM-1001'),

-- Residencias (común a todas las carreras)
('Residencias Profesionales', 'RES-9001'),
('Servicio Social', 'SER-9001'),

-- ========================================
-- INGENIERÍA EN SISTEMAS COMPUTACIONALES
-- ========================================
('Fundamentos de Programación', 'ISC-1001'),
('Programación Orientada a Objetos', 'ISC-1002'),
('Estructura de Datos', 'ISC-1003'),
('Tópicos Avanzados de Programación', 'ISC-1004'),
('Programación Web', 'ISC-1005'),
('Programación Lógica y Funcional', 'ISC-1006'),
('Lenguajes y Autómatas I', 'ISC-1007'),
('Lenguajes y Autómatas II', 'ISC-1008'),
('Base de Datos', 'ISC-2001'),
('Taller de Base de Datos', 'ISC-2002'),
('Arquitectura de Computadoras', 'ISC-2003'),
('Sistemas Operativos', 'ISC-2004'),
('Redes de Computadoras', 'ISC-2005'),
('Administración de Redes', 'ISC-2006'),
('Ingeniería de Software', 'ISC-3001'),
('Calidad de Software', 'ISC-3002'),
('Inteligencia Artificial', 'ISC-3003'),
('Graficación', 'ISC-3004'),
('Simulación', 'ISC-3005'),
('Principios Eléctricos y Aplicaciones Digitales', 'ISC-3006'),
('Fundamentos de Telecomunicaciones', 'ISC-3007'),
('Conmutación y Enrutamiento de Redes', 'ISC-3008'),
('Administración de Bases de Datos', 'ISC-3009'),
('Programación Móvil', 'ISC-4001'),
('Desarrollo de Aplicaciones Web', 'ISC-4002'),
('Seguridad Informática', 'ISC-4003'),

-- ========================================
-- INGENIERÍA INDUSTRIAL
-- ========================================
('Dibujo Industrial', 'II-1001'),
('Metrología yNormalización', 'II-1002'),
('Propiedades de los Materiales', 'II-1003'),
('Procesos de Fabricación', 'II-1004'),
('Electricidad y Electrónica Industrial', 'II-1005'),
('Estadística Inferencial I', 'II-2001'),
('Estadística Inferencial II', 'II-2002'),
('Estudio del Trabajo I', 'II-2003'),
('Estudio del Trabajo II', 'II-2004'),
('Ergonomía', 'II-2005'),
('Higiene y Seguridad Industrial', 'II-2006'),
('Investigación de Operaciones I', 'II-3001'),
('Investigación de Operaciones II', 'II-3002'),
('Control Estadístico de la Calidad', 'II-3003'),
('Sistemas de Manufactura', 'II-3004'),
('Planeación y Diseño de Instalaciones', 'II-3005'),
('Gestión de Costos', 'II-3006'),
('Administración de Operaciones I', 'II-4001'),
('Administración de Operaciones II', 'II-4002'),
('Planeación Financiera', 'II-4003'),
('Mercadotecnia', 'II-4004'),
('Relaciones Industriales', 'II-4005'),
('Logística y Cadenas de Suministro', 'II-4006'),
('Manufactura Esbelta', 'II-4007'),
('Sistemas de Gestión de la Calidad', 'II-4008'),

-- ========================================
-- INGENIERÍA EN GESTIÓN EMPRESARIAL
-- ========================================
('Fundamentos de Gestión Empresarial', 'IGE-1001'),
('Dinámica Social', 'IGE-1002'),
('Fundamentos de Física', 'IGE-1003'),
('Contabilidad Financiera', 'IGE-2001'),
('Contabilidad Administrativa', 'IGE-2002'),
('Costos Empresariales', 'IGE-2003'),
('Legislación Laboral', 'IGE-2004'),
('Derecho Empresarial', 'IGE-2005'),
('Economía Empresarial', 'IGE-3001'),
('Finanzas en las Organizaciones', 'IGE-3002'),
('Gestión del Capital Humano', 'IGE-3003'),
('Mercadotecnia', 'IGE-3004'),
('Gestión Estratégica', 'IGE-3005'),
('Habilidades Directivas I', 'IGE-3006'),
('Habilidades Directivas II', 'IGE-3007'),
('Plan de Negocios', 'IGE-4001'),
('Gestión de la Producción I', 'IGE-4002'),
('Gestión de la Producción II', 'IGE-4003'),
('Logística Empresarial', 'IGE-4004'),
('Trámites Legales y Gestión del Comercio Exterior', 'IGE-4005'),
('El Emprendedor y la Innovación', 'IGE-4006'),
('Simulación de Negocios', 'IGE-4007'),

-- ========================================
-- INGENIERÍA ELECTRÓNICA
-- ========================================
('Análisis de Circuitos Eléctricos DC', 'IE-1001'),
('Análisis de Circuitos Eléctricos AC', 'IE-1002'),
('Electrónica Analógica', 'IE-2001'),
('Electrónica Digital', 'IE-2002'),
('Mediciones Eléctricas', 'IE-2003'),
('Dispositivos Electrónicos', 'IE-2004'),
('Microcontroladores', 'IE-3001'),
('Microprocesadores', 'IE-3002'),
('Sistemas Digitales', 'IE-3003'),
('Instrumentación', 'IE-3004'),
('Máquinas Eléctricas', 'IE-3005'),
('Teoría Electromagnética', 'IE-3006'),
('Procesamiento Digital de Señales', 'IE-4001'),
('Control I', 'IE-4002'),
('Control II', 'IE-4003'),
('Comunicaciones I', 'IE-4004'),
('Comunicaciones II', 'IE-4005'),
('Sistemas Programables', 'IE-4006'),
('Redes de Computadoras', 'IE-4007'),
('Diseño Digital con VHDL', 'IE-4008'),
('Robótica', 'IE-4009'),

-- ========================================
-- INGENIERÍA MECATRÓNICA
-- ========================================
('Dibujo Mecánico', 'IM-1001'),
('Análisis de Circuitos Eléctricos', 'IM-1002'),
('Estática', 'IM-1003'),
('Dinámica', 'IM-1004'),
('Electrónica Analógica', 'IM-2001'),
('Electrónica Digital', 'IM-2002'),
('Mecánica de Materiales', 'IM-2003'),
('Termodinámica', 'IM-2004'),
('Metrología y Normalización', 'IM-2005'),
('Microcontroladores', 'IM-3001'),
('Sistemas Hidráulicos y Neumáticos', 'IM-3002'),
('Máquinas Eléctricas', 'IM-3003'),
('Manufactura Avanzada', 'IM-3004'),
('Control', 'IM-3005'),
('Programación Avanzada', 'IM-3006'),
('Robótica Industrial', 'IM-4001'),
('Automatización', 'IM-4002'),
('Sistemas de Manufactura', 'IM-4003'),
('Visión Artificial', 'IM-4004'),
('Redes Industriales', 'IM-4005'),
('Sistemas Embebidos', 'IM-4006'),
('Control CNC', 'IM-4007'),
('Administración y Técnicas de Mantenimiento', 'IM-4008'),

-- ========================================
-- INGENIERÍA EN ENERGÍAS RENOVABLES
-- ========================================
('Introducción a las Energías Renovables', 'IER-1001'),
('Termodinámica', 'IER-2001'),
('Mecánica de Fluidos', 'IER-2002'),
('Transferencia de Calor', 'IER-2003'),
('Circuitos Eléctricos', 'IER-2004'),
('Máquinas Eléctricas', 'IER-3001'),
('Electrónica de Potencia', 'IER-3002'),
('Sistemas Fotovoltaicos', 'IER-3003'),
('Energía Solar Térmica', 'IER-3004'),
('Energía Eólica', 'IER-3005'),
('Biomasa', ' IER-3006'),
('Hidráulica', 'IER-3007'),
('Sistemas Hidroeléctricos', 'IER-4001'),
('Administración de la Energía', 'IER-4002'),
('Evaluación de Proyectos de Energías Renovables', 'IER-4003'),
('Eficiencia Energética', 'IER-4004'),
('Sistemas de Almacenamiento de Energía', 'IER-4005'),
('Redes Eléctricas Inteligentes', 'IER-4006'),
('Modelado y Simulación de Sistemas Energéticos', 'IER-4007'),

-- ========================================
-- CONTADOR PÚBLICO
-- ========================================
('Introducción a la Contaduría', 'CP-1001'),
('Fundamentos de Administración', 'CP-1002'),
('Derecho Civil y Mercantil', 'CP-1003'),
('Contabilidad Básica', 'CP-2001'),
('Contabilidad Intermedia', 'CP-2002'),
('Contabilidad de Costos', 'CP-2003'),
('Contabilidad Avanzada', 'CP-2004'),
('Derecho Fiscal', 'CP-2005'),
('Matemáticas Financieras', 'CP-2006'),
('Auditoría I', 'CP-3001'),
('Auditoría II', 'CP-3002'),
('Auditoría III', 'CP-3003'),
('Impuestos I', 'CP-3004'),
('Impuestos II', 'CP-3005'),
('Finanzas I', 'CP-3006'),
('Finanzas II', 'CP-3007'),
('Normas de Información Financiera', 'CP-4001'),
('Contabilidad Gubernamental', 'CP-4002'),
('Auditoría Fiscal', 'CP-4003'),
('Administración Financiera', 'CP-4004'),
('Sistemas de Información Contable', 'CP-4005'),
('Análisis e Interpretación de Estados Financieros', 'CP-4006'),
('Presupuestos', 'CP-4007')
ON DUPLICATE KEY UPDATE nombre=VALUES(nombre);
